### ISSUE TITLE
File created, but it is empty.

### ISSUE THREAD

**Issue by Org927** [Sumanjit092/Azure-Active-Directory#1]
First of, thanks much for the script!

The file is well created and takes around 3-4 minutes, but is empty. Does it have to do with permissions to Azure (Intune) maybe?

**Comment by Sumanjit092** [comment]
Thank you for posting the problem.

Script does not require permission with Intune. You require Global Admin or Global Reader Permission on your tenant, also you require read access on your Azure Subscription.

Please review permission and let me know the the status.

**Comment by Org927** [comment]
Yes, worked well after gaining Global Reader Permission. Great work with this and thanks again!

**Comment by Sumanjit092** [comment]
Thank you for the kind words!
